# Generated by Django 5.2.7 on 2026-02-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for requesting access')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('accessed', 'Accessed')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('access_otp_sent', models.BooleanField(default=False)),
                ('access_granted_at', models.DateTimeField(blank=True, null=True)),
                ('blockchain_request_tx', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_approval_tx', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_access_tx', models.CharField(blank=True, max_length=66, null=True)),
            ],
            options={
                'verbose_name': 'Access Request',
                'verbose_name_plural': 'Access Requests',
                'db_table': 'access_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download')], default='view', max_length=10)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
            ],
            options={
                'verbose_name': 'Data Access Log',
                'verbose_name_plural': 'Data Access Logs',
                'db_table': 'data_access_log',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
