# Generated by Django 5.2.7 on 2026-02-12 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('data_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='data_management.datafile'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='access_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='access_control.accessrequest'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='data_management.datafile'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
